<div class="vbs-chat">
	<div class="the-chat">
		<table id="the_chat">
			<tr class="on">
				<td class="name owner">Josh</td>
				<td class="message owner">Welcome to my Ad!</td>
			</tr>
			<tr class="off">
				<td class="name">Penny</td>
				<td class="message">Thats a really nice boat, Josh!</td>
			</tr>
			<tr class="on">
				<td class="name owner">Josh</td>
				<td class="message owner">Thanks!  Wanna buy it?!</td>
			</tr>
			<tr class="off">
				<td class="name">Penny</td>
				<td class="message">Well, I guess that depends...</td>
			</tr>
			<tr class="on">
				<td class="name">Penny</td>
				<td class="message">How much are you asking?</td>
			</tr>
		</table>
	</div>
	<div class="your-message">Your Message</div>
	<div class="user-input"><textarea name="chat-input"></textarea></div>
	<div class="button-and-login">
		<div class="send"><input type="submit" value="Send"></div>
		<div class="login-register">
			<div class="message">You must be logged in to post.</div>
			<div class="links"><a href="#">Log in</a> or <a href="#">Sign-Up</a></div>
		</div>
	</div>
</div>
